### ISSUE TITLE
fix/기능 미완성

### ISSUE THREAD

**Issue by blcklamb** [pick-time/pick-time-fe#101]
# Task
### feature
- [x] 쿠폰 Mock data 정리
- [x] 쿠폰이 추가되고 바로 반영되지 않음
- [x] 카드, 선물, 쿠폰을 등록하고 주는 사람 엔딩 페이지로 이동할 수 있는 인터렉션이 없음
    - [x] 리스트 작성 POST api
### style
- [x] header z-index 조정, dimmed 처리 시 같이 처리가 되지 않음
- [x] 레이아웃 중앙 정렬
- [ ] 카드 만들기 레이아웃

### 모바일 확인 요망
- [ ] 쿠폰 생성시 배경색을 선택하는 컬러칩이 깨진 상태로 보임
- [ ] 선물 수정 모달창 스타일링이 수정되어야함
